from BaseClasses import Item, ItemClassification
import typing

next_ap_id = 500000

class ItemData(typing.NamedTuple):
    id: typing.Optional[int]
    classification: ItemClassification

def get_data(item_classification: ItemClassification) -> ItemData:
    global next_ap_id
    data = ItemData(next_ap_id, item_classification)
    next_ap_id += 1
    return data

class SonicUnleashedItem(Item):
    game = "Sonic Unleashed"

item_table = {
    # Medals - Progression
    "Sun Medal": get_data(ItemClassification.progression),
    "Moon Medal": get_data(ItemClassification.progression),

    # Upgrades - Progression
    "Air Boost": get_data(ItemClassification.progression),
    "Light Speed": get_data(ItemClassification.progression),
    "Stomping": get_data(ItemClassification.progression),
    "Wall Jump": get_data(ItemClassification.progression),

    # Gaia Keys ??? A verifier si vrai item - Progression

    # Edible Items - Useful
    "Apple": get_data(ItemClassification.useful),
    "Aurora Oil": get_data(ItemClassification.useful),
    "Baguetti": get_data(ItemClassification.useful),
    "Banana": get_data(ItemClassification.useful),
    "Baobab Fruit": get_data(ItemClassification.useful),
    "Big G Steak": get_data(ItemClassification.useful),
    "Boelk Cream": get_data(ItemClassification.useful),
    "Brainiac Dog": get_data(ItemClassification.useful),
    "Breezy Dog": get_data(ItemClassification.useful),
    "Broiled Ibanga": get_data(ItemClassification.useful),
    "Candy": get_data(ItemClassification.useful),
    "Canned Horror": get_data(ItemClassification.useful),
    "Canned Juice": get_data(ItemClassification.useful),
    "Caqueo": get_data(ItemClassification.useful),
    "Chai": get_data(ItemClassification.useful),
    "Chao Chugger": get_data(ItemClassification.useful),
    "Cheese": get_data(ItemClassification.useful),
    "Chili Dog": get_data(ItemClassification.useful),
    "Chilly Dog": get_data(ItemClassification.useful),
    "Chirp Peas": get_data(ItemClassification.useful),
    "Chocolate": get_data(ItemClassification.useful),
    "Cookie": get_data(ItemClassification.useful),
    "Curry": get_data(ItemClassification.useful),
    "Doggone Dog": get_data(ItemClassification.useful),
    "Dondora Fruit": get_data(ItemClassification.useful),
    "Donut": get_data(ItemClassification.useful),
    "Dureek": get_data(ItemClassification.useful),
    "Egg Candy": get_data(ItemClassification.useful),
    "Egg Dog": get_data(ItemClassification.useful),
    "Egg Puff": get_data(ItemClassification.useful),
    "Egg-squisite Lunch": get_data(ItemClassification.useful),
    "Elastic Ice Cream": get_data(ItemClassification.useful),
    "Empire Coffee": get_data(ItemClassification.useful),
    "Fried Chicken": get_data(ItemClassification.useful),
    "Fried Suncake": get_data(ItemClassification.useful),
    "Grapes": get_data(ItemClassification.useful),
    "Hamburger": get_data(ItemClassification.useful),
    "Hero Sandwich": get_data(ItemClassification.useful),
    "Historic Dog": get_data(ItemClassification.useful),
    "Kebabwich": get_data(ItemClassification.useful),
    "Lemon": get_data(ItemClassification.useful),
    "Lin's Meat Buns": get_data(ItemClassification.useful),
    "Live Honker": get_data(ItemClassification.useful),
    "Melloyam": get_data(ItemClassification.useful),
    "Molsk": get_data(ItemClassification.useful),
    "Nuclear Taquo": get_data(ItemClassification.useful),
    "Orange": get_data(ItemClassification.useful),
    "Paaf": get_data(ItemClassification.useful),
    "Pasta alla Paccico": get_data(ItemClassification.useful),
    "Peach": get_data(ItemClassification.useful),
    "Peach Buns": get_data(ItemClassification.useful),
    "Perma-Meat": get_data(ItemClassification.useful),
    "Pitch Nuts": get_data(ItemClassification.useful),
    "Pizza": get_data(ItemClassification.useful),
    "Popcake": get_data(ItemClassification.useful),
    "Poppin' Eggcorn": get_data(ItemClassification.useful),
    "Power Vitamin": get_data(ItemClassification.useful),
    "Prehistoric Ice": get_data(ItemClassification.useful),
    "Sandwich": get_data(ItemClassification.useful),
    "Sandwich?": get_data(ItemClassification.useful),
    "Sandy Dog": get_data(ItemClassification.useful),
    "Seafood Dog": get_data(ItemClassification.useful),
    "Scorcher Dog": get_data(ItemClassification.useful),
    "Smoked Mohn": get_data(ItemClassification.useful),
    "Sparkle Gelatin": get_data(ItemClassification.useful),
    "Strawberry Cake": get_data(ItemClassification.useful),
    "Sundae Supreme": get_data(ItemClassification.useful),
    "Tomato": get_data(ItemClassification.useful),
    "Tropic Juice": get_data(ItemClassification.useful),
    "Urban Dog": get_data(ItemClassification.useful),
    "Wang's Box Lunch": get_data(ItemClassification.useful),
    "Wang's Noodles": get_data(ItemClassification.useful),

    # Misc - Useful 
    "Super Ring": get_data(ItemClassification.useful), #10 Rings dans le total
    "Chaos Orb": get_data(ItemClassification.useful), #Incremente de l'XP 
    "1 UP": get_data(ItemClassification.useful),

    # Souvenir - Fillers
    "Photo Frame (Apotos)": get_data(ItemClassification.filler),
    "Miniature Flag (Apotos)": get_data(ItemClassification.filler),
    "Potpourri": get_data(ItemClassification.filler),
    "Lace Tablecoth": get_data(ItemClassification.filler),
    "Water Jug": get_data(ItemClassification.filler),
    "Photo Frame (Spagonia)": get_data(ItemClassification.filler), 
    "Miniature Flag (Spagonia)": get_data(ItemClassification.filler),
    "Maschera": get_data(ItemClassification.filler),
    "Spagonian Glass": get_data(ItemClassification.filler),
    "Spagonian Cameo": get_data(ItemClassification.filler),
    "Photo Frame (Chun-Nan)": get_data(ItemClassification.filler),
    "Miniature Flag (Chun-Nan)": get_data(ItemClassification.filler),
    "Censer": get_data(ItemClassification.filler),
    "Lantern": get_data(ItemClassification.filler),
    "Urn": get_data(ItemClassification.filler),
    "Photo Frame (Mazuri)": get_data(ItemClassification.filler),
    "Miniature Flag (Mazuri)": get_data(ItemClassification.filler),
    "Earthenware Pot": get_data(ItemClassification.filler),
    "Equine Carving": get_data(ItemClassification.filler),
    "Talismanic Mask": get_data(ItemClassification.filler),
    "Photo Frame (Holoska)": get_data(ItemClassification.filler),
    "Miniature Flag (Holoska)": get_data(ItemClassification.filler),
    "Nesting Dolls": get_data(ItemClassification.filler),
    "Model Sled": get_data(ItemClassification.filler),
    "Whale Ornament": get_data(ItemClassification.filler),
    "Photo Frame (Shamar)": get_data(ItemClassification.filler),
    "Miniature Flag (Shamar)": get_data(ItemClassification.filler),
    "Shamaran Sand": get_data(ItemClassification.filler),
    "Lunisolar Charm": get_data(ItemClassification.filler),
    "Carpet": get_data(ItemClassification.filler),
    "Photo Frame (Adabat)": get_data(ItemClassification.filler),
    "Miniature Flag (Adabat)": get_data(ItemClassification.filler),
    "Hammock": get_data(ItemClassification.filler),
    "Chehaya Charm": get_data(ItemClassification.filler),
    "Anji Sculpture": get_data(ItemClassification.filler),
    "Photo Frame (Empire City)": get_data(ItemClassification.filler),
    "Miniature Flag (Empire City)": get_data(ItemClassification.filler),
    "Magazine": get_data(ItemClassification.filler),
    "Jenny": get_data(ItemClassification.filler),
    "Jack-o'-Lantern": get_data(ItemClassification.filler),
    "Photo Frame (Eggmanland)": get_data(ItemClassification.filler),
    "Miniature Flag (Eggmanland)": get_data(ItemClassification.filler),
    "Egg Baloon": get_data(ItemClassification.filler),
    "Eggman Poster": get_data(ItemClassification.filler),
    "Egg Goggles": get_data(ItemClassification.filler),

    # Videotapes - Filler
    "Opening": get_data(ItemClassification.filler),
    "A New Journey": get_data(ItemClassification.filler),
    "Special Sundae": get_data(ItemClassification.filler),
    "The First Night": get_data(ItemClassification.filler),
    "Tails in Trouble!": get_data(ItemClassification.filler),
    "To Spagonia!": get_data(ItemClassification.filler),
    "Kidnapped": get_data(ItemClassification.filler),
    "Same As Ever": get_data(ItemClassification.filler),
    "Gaia Manuscripts": get_data(ItemClassification.filler),
    "Eggman Again": get_data(ItemClassification.filler),
    "The Egg Beetle": get_data(ItemClassification.filler),
    "Temple Entrance": get_data(ItemClassification.filler),
    "Temple Activated!": get_data(ItemClassification.filler),
    "Planet Pieces": get_data(ItemClassification.filler),
    "Tails' Report": get_data(ItemClassification.filler),
    "Amy's Mistake": get_data(ItemClassification.filler),
    "Midnight Dance": get_data(ItemClassification.filler),
    "Rescuing Amy": get_data(ItemClassification.filler),
    "The Divine Beast": get_data(ItemClassification.filler),
    "The Key": get_data(ItemClassification.filler),
    "Chun-Nan Temple": get_data(ItemClassification.filler),
    "Back to Normal": get_data(ItemClassification.filler),
    "Eggman's Idea": get_data(ItemClassification.filler),
    "Spagonian Temple": get_data(ItemClassification.filler),
    "Guiding Pulse": get_data(ItemClassification.filler),
    "A Monster on Ice": get_data(ItemClassification.filler),
    "Holoskan Temple": get_data(ItemClassification.filler),
    "Project Dark Gaia": get_data(ItemClassification.filler),
    "Shamaran Temple": get_data(ItemClassification.filler),
    "Chip's Change": get_data(ItemClassification.filler),
    "Chip's Memories": get_data(ItemClassification.filler),
    "No Reason": get_data(ItemClassification.filler),
    "Eggmanland": get_data(ItemClassification.filler),
    "The Final Temple": get_data(ItemClassification.filler),
    "The 7th Continent": get_data(ItemClassification.filler),
    "Congratulions": get_data(ItemClassification.filler),
    "Pickle's Message": get_data(ItemClassification.filler),
    "The Egg Dragoon": get_data(ItemClassification.filler),
    "Planet's End": get_data(ItemClassification.filler),
    "Dark Gaia Appears": get_data(ItemClassification.filler),
    "Shrines in Flight": get_data(ItemClassification.filler),
    "Hour Of Awakening": get_data(ItemClassification.filler),
    "Charge!": get_data(ItemClassification.filler),
    "Let's Finish This!": get_data(ItemClassification.filler),
    "Spreading Darkness": get_data(ItemClassification.filler),
    "Dark World": get_data(ItemClassification.filler),
    "Hope and Despair": get_data(ItemClassification.filler),
    "The Final Form": get_data(ItemClassification.filler),
    "Darkness and Light": get_data(ItemClassification.filler),
    "Annihilation": get_data(ItemClassification.filler),
    "A Score Settled": get_data(ItemClassification.filler),
    "Rekindled Light": get_data(ItemClassification.filler),
    "Begin Anew": get_data(ItemClassification.filler),
    "Save the Speech": get_data(ItemClassification.filler),
    "To the Surface": get_data(ItemClassification.filler),
    "Always": get_data(ItemClassification.filler),
    "Sonic and Chip (in Chun-Nan)": get_data(ItemClassification.filler),
    "Sonic and Chip (in Holoska)": get_data(ItemClassification.filler),
    "Sonic and Chip (in Adabat)": get_data(ItemClassification.filler),

    # Art Books - Filler
    "Apotos #1": get_data(ItemClassification.filler),
    "Apotos #2": get_data(ItemClassification.filler),
    "Spagonia #1": get_data(ItemClassification.filler),
    "Spagonia #2": get_data(ItemClassification.filler),
    "Mazuri #1": get_data(ItemClassification.filler),
    "Mazuri #2": get_data(ItemClassification.filler),
    "Chun-Nan #1": get_data(ItemClassification.filler),
    "Chun-Nan #2": get_data(ItemClassification.filler),
    "Holoska #1": get_data(ItemClassification.filler),
    "Holoska #2": get_data(ItemClassification.filler),
    "Shamar #1": get_data(ItemClassification.filler),
    "Shamar #2": get_data(ItemClassification.filler),
    "Shamar #3": get_data(ItemClassification.filler),
    "Empire City #1": get_data(ItemClassification.filler),
    "Adabat #1": get_data(ItemClassification.filler),
    "Adabat #2": get_data(ItemClassification.filler),
    "Eggmanland #1": get_data(ItemClassification.filler),
    "Eggmanland #2": get_data(ItemClassification.filler),
    "Eggman's Hideout": get_data(ItemClassification.filler),
    "Pickle's Lab (Shamar)": get_data(ItemClassification.filler),
    "Opening #1": get_data(ItemClassification.filler),
    "Opening #2": get_data(ItemClassification.filler),
    "OPening #3": get_data(ItemClassification.filler),
    "People of Apotos #1": get_data(ItemClassification.filler),
    "Anastasia": get_data(ItemClassification.filler),
    "People of Apotos #2": get_data(ItemClassification.filler),
    "People of Spagonia #1": get_data(ItemClassification.filler),
    "Franco": get_data(ItemClassification.filler),
    "Otto": get_data(ItemClassification.filler),
    "Dora": get_data(ItemClassification.filler),
    "People of Spagonia #2": get_data(ItemClassification.filler),
    "People of Chun-nan": get_data(ItemClassification.filler),
    "Chun": get_data(ItemClassification.filler),
    "Zonshen": get_data(ItemClassification.filler),
    "People of Mazuri #1": get_data(ItemClassification.filler),
    "Yaya": get_data(ItemClassification.filler),
    "Gwek": get_data(ItemClassification.filler),
    "People of Mazuri #2": get_data(ItemClassification.filler),
    "People of Holoska": get_data(ItemClassification.filler),
    "Sarianna": get_data(ItemClassification.filler),
    "Jari-Pekka": get_data(ItemClassification.filler),
    "People of Shamar": get_data(ItemClassification.filler),
    "Hizir": get_data(ItemClassification.filler),
    "Yasmine": get_data(ItemClassification.filler),
    "Layla": get_data(ItemClassification.filler),
    "People of Empire City": get_data(ItemClassification.filler),
    "Louie Montaine": get_data(ItemClassification.filler),
    "Li'l Kate": get_data(ItemClassification.filler),
    "People of Adabat #1": get_data(ItemClassification.filler),
    "Kaeo": get_data(ItemClassification.filler),
    "People of Adabat #2": get_data(ItemClassification.filler),
    "Professor Pickle": get_data(ItemClassification.filler),
    "Prof Pickle's Asst.": get_data(ItemClassification.filler),
    "Ice Cream Vendor": get_data(ItemClassification.filler),
    "Hot Dog Vendor #1": get_data(ItemClassification.filler),
    "Hot Dog Vendor #2": get_data(ItemClassification.filler),
    "Wentos": get_data(ItemClassification.filler),
    "Interceptor": get_data(ItemClassification.filler),
    "Egg Burst": get_data(ItemClassification.filler),
    "Thunder Bail": get_data(ItemClassification.filler),
    "Gold Aero-Cannon": get_data(ItemClassification.filler),
    "Egg Shooter": get_data(ItemClassification.filler),
    "Egg Blizzard": get_data(ItemClassification.filler),
    "Dark Bat Sniper": get_data(ItemClassification.filler),
    "Big Mother": get_data(ItemClassification.filler),
    "Dark Eel": get_data(ItemClassification.filler),
    "Titan": get_data(ItemClassification.filler),
    "Killer Bee": get_data(ItemClassification.filler),
    "Egg Devil Ray": get_data(ItemClassification.filler),
    "Dark Moray": get_data(ItemClassification.filler),
    "Dark Gaia": get_data(ItemClassification.filler),

    # Music Records - Filler
    "Orchestral Theme - World Adventure": get_data(ItemClassification.filler),
    "Vocal Theme - Endless Possibility": get_data(ItemClassification.filler),
    "Dear My Friend - Ending Theme": get_data(ItemClassification.filler),
    "Windmill Isle Suburbs - Day": get_data(ItemClassification.filler),
    "Windmill Isle - Day": get_data(ItemClassification.filler),
    "Savannah Citadel - Day": get_data(ItemClassification.filler),
    "Cool Edge - Day": get_data(ItemClassification.filler),
    "Rooftop Run - Day": get_data(ItemClassification.filler),
    "Dragon Road - Day": get_data(ItemClassification.filler),
    "Arid Sands - Day": get_data(ItemClassification.filler),
    "Skyscraper Scamper - Day": get_data(ItemClassification.filler),
    "Jungle Joyride - Day": get_data(ItemClassification.filler),
    "Eggmanland - Day": get_data(ItemClassification.filler),
    "Werehog Battle Theme": get_data(ItemClassification.filler),
    "vs. Titan & Big Mother": get_data(ItemClassification.filler),
    "Windmill Isle - Night": get_data(ItemClassification.filler),
    "Intro: Windmill Isle - Night": get_data(ItemClassification.filler),
    "Savannah Citadel - Night": get_data(ItemClassification.filler),
    "Intro: Savannah Citadel - Night": get_data(ItemClassification.filler),
    "Cool Edge - Night": get_data(ItemClassification.filler),
    "Intro: Cool Edge - Night": get_data(ItemClassification.filler),
    "Rooftop Run - Night": get_data(ItemClassification.filler),
    "Intro: Rooftop Run - Night": get_data(ItemClassification.filler),
    "Dragon Road - Night": get_data(ItemClassification.filler),
    "Intro: Dragon Road - Night": get_data(ItemClassification.filler),
    "Arid Sands - Night": get_data(ItemClassification.filler),
    "Intro: Arid Sands - Night": get_data(ItemClassification.filler),
    "Skyscraper Scamper - Night": get_data(ItemClassification.filler),
    "Intro: Skyscraper Scamper - Night": get_data(ItemClassification.filler),
    "Intro: Jungle Joyride - Night": get_data(ItemClassification.filler),
    "Jungle Joyride - Night": get_data(ItemClassification.filler),
    "Eggmanland - Night": get_data(ItemClassification.filler),
    "Boss Battle": get_data(ItemClassification.filler),
    "Boss Battle": get_data(ItemClassification.filler),
    "vs. Egg Dragoon": get_data(ItemClassification.filler),
    "vs. Dark Gaia": get_data(ItemClassification.filler),
    "Super Sonic vs. Dark Gaia": get_data(ItemClassification.filler),
    "Tornado Defense - 1st Battle": get_data(ItemClassification.filler),
    "Tornado Defense - 2nd Battle": get_data(ItemClassification.filler),
    "Apotos - Day": get_data(ItemClassification.filler),
    "Apotos - Night": get_data(ItemClassification.filler),
    "Mazuri - Day": get_data(ItemClassification.filler),
    "Mazuri - Night": get_data(ItemClassification.filler),
    "Holoska - Day": get_data(ItemClassification.filler),
    "Holoska - Night": get_data(ItemClassification.filler),
    "Spagonia - Day": get_data(ItemClassification.filler),
    "Spagonia - Night": get_data(ItemClassification.filler),
    "Chun-nan - Day": get_data(ItemClassification.filler),
    "Chun-nan -Night": get_data(ItemClassification.filler),
    "Shamar - Day": get_data(ItemClassification.filler),
    "Shamar - Night": get_data(ItemClassification.filler),
    "Empire City - Day": get_data(ItemClassification.filler),
    "Empire City - Night": get_data(ItemClassification.filler),
    "Adabat - Day": get_data(ItemClassification.filler),
    "Adabat - Night": get_data(ItemClassification.filler),
    "Eggmanland Entrance": get_data(ItemClassification.filler),
    "Result Screen": get_data(ItemClassification.filler),
    "Result Screen E-Rank": get_data(ItemClassification.filler),
    "Stage Clear": get_data(ItemClassification.filler),
    "Boss Stage Clear": get_data(ItemClassification.filler),
    "Opening Movie - Part 1": get_data(ItemClassification.filler),
    "Opening Movie - Part 2": get_data(ItemClassification.filler),

    # Professor's Lab  - Filler
    "TV": get_data(ItemClassification.filler),
    "Bookshelf": get_data(ItemClassification.filler),
    "Gramophone": get_data(ItemClassification.filler),
    "Audio System": get_data(ItemClassification.filler),

    # Other Fillers
    "Heal Ring": get_data(ItemClassification.filler),
    "Power Shield": get_data(ItemClassification.filler),
    "Super Claw": get_data(ItemClassification.filler),
    "Shield Charge": get_data(ItemClassification.filler)
}

key_items = {
    "Moon medal": 200,
    "Sun medal": 200
}

filler_items_weight = {
    "Super Claw": 1
}