from BaseClasses import Item, ItemClassification
import typing

next_ap_id = 500000

class ItemData(typing.NamedTuple):
    id: typing.Optional[int]
    classification: ItemClassification

def get_data(item_classification: ItemClassification) -> ItemData:
    global next_ap_id
    data = ItemData(next_ap_id, item_classification)
    next_ap_id += 1
    return data

class SonicUnleashedItem(Item):
    game = "Sonic Unleashed"

item_table = {
    # Medals - Progression
    "Sun Medal": BASE_ID,
    "Moon Medal": BASE_ID + 1,

    # Upgrades - Progression
    "Air Boost Shoes": BASE_ID + 2,
    "Light Speed Shoes": BASE_ID + 3,
    "Stomping Shoes": BASE_ID + 4,
    "Wall Jump Shoes": BASE_ID + 5,

    # Gaia Keys ??? A verifier si vrai item - Progression

    # Edible Items - Useful
    "Apple": BASE_ID + 6,
    "Aurora Oil": BASE_ID + 7,
    "Baguetti": BASE_ID + 8,
    "Banana": BASE_ID + 9,
    "Baobab Fruit": BASE_ID + 10,
    "Big G Steak": BASE_ID + 11,
    "Boelk Cream": BASE_ID + 12,
    "Brainiac Dog": BASE_ID + 13,
    "Breezy Dog": BASE_ID + 14,
    "Broiled Ibanga": BASE_ID + 15,
    "Candy": BASE_ID + 16,
    "Canned Horror": BASE_ID + 17,
    "Canned Juice": BASE_ID + 18,
    "Caqueo": BASE_ID + 19,
    "Chai": BASE_ID + 20,
    "Chao Chugger": BASE_ID + 21,
    "Cheese": BASE_ID + 22,
    "Chili Dog": BASE_ID + 23,
    "Chilly Dog": BASE_ID + 24,
    "Chirp Peas": BASE_ID + 25,
    "Chocolate": BASE_ID + 26,
    "Cookie": BASE_ID + 27,
    "Curry": BASE_ID + 28,
    "Doggone Dog": BASE_ID + 29,
    "Dondora Fruit": BASE_ID + 30,
    "Donut": BASE_ID + 31,
    "Dureek": BASE_ID + 32,
    "Egg Candy": BASE_ID + 33,
    "Egg Dog": BASE_ID + 34,
    "Egg Puff": BASE_ID + 35,
    "Egg-squisite Lunch": BASE_ID + 36,
    "Elastic Ice Cream": BASE_ID + 37,
    "Empire Coffee": BASE_ID + 38,
    "Fried Chicken": BASE_ID + 39,
    "Fried Suncake": BASE_ID + 40,
    "Grapes": BASE_ID + 41,
    "Hamburger": BASE_ID + 42,
    "Hero Sandwich": BASE_ID + 43,
    "Historic Dog": BASE_ID + 44,
    "Kebabwich": BASE_ID + 45,
    "Lemon": BASE_ID + 46,
    "Lin's Meat Buns": BASE_ID + 47,
    "Live Honker": BASE_ID + 48,
    "Melloyam": BASE_ID + 49,
    "Molsk": BASE_ID + 50,
    "Nuclear Taquo": BASE_ID + 51,
    "Orange": BASE_ID + 52,
    "Paaf": BASE_ID + 53,
    "Pasta alla Paccico": BASE_ID + 54,
    "Peach": BASE_ID + 55,
    "Peach Buns": BASE_ID + 56,
    "Perma-Meat": BASE_ID + 57,
    "Pitch Nuts": BASE_ID + 58,
    "Pizza": BASE_ID + 59,
    "Popcake": BASE_ID + 60,
    "Poppin' Eggcorn": BASE_ID + 61,
    "Power Vitamin": BASE_ID + 62,
    "Prehistoric Ice": BASE_ID + 63,
    "Sandwich": BASE_ID + 64,
    "Sandwich?": BASE_ID + 65,
    "Sandy Dog": BASE_ID + 66,
    "Seafood Dog": BASE_ID + 67,
    "Scorcher Dog": BASE_ID + 68,
    "Smoked Mohn": BASE_ID + 69,
    "Sparkle Gelatin": BASE_ID + 70,
    "Strawberry Cake": BASE_ID + 71,
    "Sundae Supreme": BASE_ID + 72,
    "Tomato": BASE_ID + 73,
    "Tropic Juice": BASE_ID + 74,
    "Urban Dog": BASE_ID + 75,
    "Wang's Box Lunch": BASE_ID + 76,
    "Wang's Noodles": BASE_ID + 77,

    # Misc - Useful 
    "Super Ring": 1, #10 Rings dans le total
    "Chaos Orb": 1, #Incremente de l'XP 
    "1 UP": 1,

    # Souvenir - Fillers
    "Photo Frame (Apotos)": BASE_ID + 78,
    "Miniature Flag (Apotos)": BASE_ID + 79,
    "Potpourri": BASE_ID + 80,
    "Lace Tablecoth": BASE_ID + 81,
    "Water Jug": BASE_ID + 82,
    "Photo Frame (Spagonia)": BASE_ID + 83, 
    "Miniature Flag (Spagonia)": BASE_ID + 84,
    "Maschera": BASE_ID + 85,
    "Spagonian Glass": BASE_ID + 86,
    "Spagonian Cameo": BASE_ID + 87,
    "Photo Frame (Chun-Nan)": BASE_ID + 88,
    "Miniature Flag (Chun-Nan)": BASE_ID + 89,
    "Censer": BASE_ID + 90,
    "Lantern": BASE_ID + 91,
    "Urn": BASE_ID + 92,
    "Photo Frame (Mazuri)": BASE_ID + 93,
    "Miniature Flag (Mazuri)": BASE_ID + 94,
    "Earthenware Pot": BASE_ID + 95,
    "Equine Carving": BASE_ID + 96,
    "Talismanic Mask": BASE_ID + 97,
    "Photo Frame (Holoska)": BASE_ID + 98,
    "Miniature Flag (Holoska)": BASE_ID + 99,
    "Nesting Dolls": BASE_ID + 100,
    "Model Sled": BASE_ID + 101,
    "Whale Ornament": BASE_ID + 102,
    "Photo Frame (Shamar)": BASE_ID + 103,
    "Miniature Flag (Shamar)": BASE_ID + 104,
    "Shamaran Sand": BASE_ID + 105,
    "Lunisolar Charm": BASE_ID + 106,
    "Carpet": BASE_ID + 107,
    "Photo Frame (Adabat)": BASE_ID + 108,
    "Miniature Flag (Adabat)": BASE_ID + 109,
    "Hammock": BASE_ID + 110,
    "Chehaya Charm": BASE_ID + 111,
    "Anji Sculpture": BASE_ID + 112,
    "Photo Frame (Empire City)": BASE_ID + 113,
    "Miniature Flag (Empire City)": BASE_ID + 114,
    "Magazine": BASE_ID + 115,
    "Jenny": BASE_ID + 116,
    "Jack-o'-Lantern": BASE_ID + 117,
    "Photo Frame (Eggmanland)": BASE_ID + 118,
    "Miniature Flag (Eggmanland)": BASE_ID + 119,
    "Egg Baloon": BASE_ID + 120,
    "Eggman Poster": BASE_ID + 121,
    "Egg Goggles": BASE_ID + 122,

    # Videotapes - Filler
    "Opening": BASE_ID + 123,
    "A New Journey": BASE_ID + 124,
    "Special Sundae": BASE_ID + 125,
    "The First Night": BASE_ID + 126,
    "Tails in Trouble!": BASE_ID + 127,
    "To Spagonia!": BASE_ID + 128,
    "Kidnapped": BASE_ID + 129,
    "Same As Ever": BASE_ID + 130,
    "Gaia Manuscripts": BASE_ID + 131,
    "Eggman Again": BASE_ID + 132,
    "The Egg Beetle": BASE_ID + 133,
    "Temple Entrance": BASE_ID + 134,
    "Temple Activated!": BASE_ID + 135,
    "Planet Pieces": BASE_ID + 136,
    "Tails' Report": BASE_ID + 137,
    "Amy's Mistake": BASE_ID + 138,
    "Midnight Dance": BASE_ID + 139,
    "Rescuing Amy": BASE_ID + 140,
    "The Divine Beast": BASE_ID + 141,
    "The Key": BASE_ID + 142,
    "Chun-Nan Temple": BASE_ID + 143,
    "Back to Normal": BASE_ID + 144,
    "Eggman's Idea": BASE_ID + 145,
    "Spagonian Temple": BASE_ID + 146,
    "Guiding Pulse": BASE_ID + 147,
    "A Monster on Ice": BASE_ID + 148,
    "Holoskan Temple": BASE_ID + 149,
    "Project Dark Gaia": BASE_ID + 150,
    "Shamaran Temple": BASE_ID + 151,
    "Chip's Change": BASE_ID + 152,
    "Chip's Memories": BASE_ID + 153,
    "No Reason": BASE_ID + 154,
    "Eggmanland": BASE_ID + 155,
    "The Final Temple": BASE_ID + 156,
    "The 7th Continent": BASE_ID + 157,
    "Congratulions": BASE_ID + 158,
    "Pickle's Message": BASE_ID + 159,
    "The Egg Dragoon": BASE_ID + 160,
    "Planet's End": BASE_ID + 161,
    "Dark Gaia Appears": BASE_ID + 162,
    "Shrines in Flight": BASE_ID + 163,
    "Hour Of Awakening": BASE_ID + 164,
    "Charge!": BASE_ID + 165,
    "Let's Finish This!": BASE_ID + 166,
    "Spreading Darkness": BASE_ID + 167,
    "Dark World": BASE_ID + 168,
    "Hope and Despair": BASE_ID + 169,
    "The Final Form": BASE_ID + 170,
    "Darkness and Light": BASE_ID + 171,
    "Annihilation": BASE_ID + 172,
    "A Score Settled": BASE_ID + 173,
    "Rekindled Light": BASE_ID + 174,
    "Begin Anew": BASE_ID + 175,
    "Save the Speech": BASE_ID + 176,
    "To the Surface": BASE_ID + 177,
    "Always": BASE_ID + 178,
    "Sonic and Chip (in Chun-Nan)": BASE_ID + 179,
    "Sonic and Chip (in Holoska)": BASE_ID + 180,
    "Sonic and Chip (in Adabat)": BASE_ID + 181,

    # Art Books - Filler
    "Apotos #1": BASE_ID + 182,
    "Apotos #2": BASE_ID + 183,
    "Spagonia #1": BASE_ID + 184,
    "Spagonia #2": BASE_ID + 185,
    "Mazuri #1": BASE_ID + 186,
    "Mazuri #2": BASE_ID + 187,
    "Chun-Nan #1": BASE_ID + 188,
    "Chun-Nan #2": BASE_ID + 189,
    "Holoska #1": BASE_ID + 190,
    "Holoska #2": BASE_ID + 191,
    "Shamar #1": BASE_ID + 192,
    "Shamar #2": BASE_ID + 193,
    "Shamar #3": BASE_ID + 194,
    "Empire City #1": BASE_ID + 195,
    "Adabat #1": BASE_ID + 196,
    "Adabat #2": BASE_ID + 197,
    "Eggmanland #1": BASE_ID + 198,
    "Eggmanland #2": BASE_ID + 199,
    "Eggman's Hideout": BASE_ID + 200,
    "Pickle's Lab (Shamar)": BASE_ID + 201,
    "Opening #1": BASE_ID + 202,
    "Opening #2": BASE_ID + 203,
    "OPening #3": BASE_ID + 204,
    "People of Apotos #1": BASE_ID + 205,
    "Anastasia": BASE_ID + 206,
    "People of Apotos #2": BASE_ID + 207,
    "People of Spagonia #1": BASE_ID + 208,
    "Franco": BASE_ID + 209,
    "Otto": BASE_ID + 210,
    "Dora": BASE_ID + 211,
    "People of Spagonia #2": BASE_ID + 212,
    "People of Chun-nan": BASE_ID + 213,
    "Chun": BASE_ID + 214,
    "Zonshen": BASE_ID + 215,
    "People of Mazuri #1": BASE_ID + 216,
    "Yaya": BASE_ID + 217,
    "Gwek": BASE_ID + 218,
    "People of Mazuri #2": BASE_ID + 219,
    "People of Holoska": BASE_ID + 220,
    "Sarianna": BASE_ID + 221,
    "Jari-Pekka": BASE_ID + 222,
    "People of Shamar": BASE_ID + 223,
    "Hizir": BASE_ID + 224,
    "Yasmine": BASE_ID + 225,
    "Layla": BASE_ID + 226,
    "People of Empire City": BASE_ID + 227,
    "Louie Montaine": BASE_ID + 228,
    "Li'l Kate": BASE_ID + 229,
    "People of Adabat #1": BASE_ID + 230,
    "Kaeo": BASE_ID + 231,
    "People of Adabat #2": BASE_ID + 232,
    "Professor Pickle": BASE_ID + 233,
    "Prof Pickle's Asst.": BASE_ID + 234,
    "Ice Cream Vendor": BASE_ID + 235,
    "Hot Dog Vendor #1": BASE_ID + 236,
    "Hot Dog Vendor #2": BASE_ID + 237,
    "Wentos": BASE_ID + 238,
    "Interceptor": BASE_ID + 239,
    "Egg Burst": BASE_ID + 240,
    "Thunder Bail": BASE_ID + 241,
    "Gold Aero-Cannon": BASE_ID + 242,
    "Egg Shooter": BASE_ID + 243,
    "Egg Blizzard": BASE_ID + 244,
    "Dark Bat Sniper": BASE_ID + 245,
    "Big Mother": BASE_ID + 246,
    "Dark Eel": BASE_ID + 247,
    "Titan": BASE_ID + 248,
    "Killer Bee": BASE_ID + 249,
    "Egg Devil Ray": BASE_ID + 250,
    "Dark Moray": BASE_ID + 251,
    "Dark Gaia": BASE_ID + 252,

    # Music Records - Filler
    "Orchestral Theme - World Adventure": BASE_ID + 253,
    "Vocal Theme - Endless Possibility": BASE_ID + 254,
    "Dear My Friend - Ending Theme": BASE_ID + 255,
    "Windmill Isle Suburbs - Day": BASE_ID + 256,
    "Windmill Isle - Day": BASE_ID + 257,
    "Savannah Citadel - Day": BASE_ID + 258,
    "Cool Edge - Day": BASE_ID + 259,
    "Rooftop Run - Day": BASE_ID + 260,
    "Dragon Road - Day": BASE_ID + 261,
    "Arid Sands - Day": BASE_ID + 262,
    "Skyscraper Scamper - Day": BASE_ID + 263,
    "Jungle Joyride - Day": BASE_ID + 264,
    "Eggmanland - Day": BASE_ID + 265,
    "Werehog Battle Theme": BASE_ID + 266,
    "vs. Titan & Big Mother": BASE_ID + 267,
    "Windmill Isle - Night": BASE_ID + 268,
    "Intro: Windmill Isle - Night": BASE_ID + 269,
    "Savannah Citadel - Night": BASE_ID + 270,
    "Intro: Savannah Citadel - Night": BASE_ID + 271,
    "Cool Edge - Night": BASE_ID + 271,
    "Intro: Cool Edge - Night": BASE_ID + 272,
    "Rooftop Run - Night": BASE_ID + 273,
    "Intro: Rooftop Run - Night": BASE_ID + 274,
    "Dragon Road - Night": BASE_ID + 275,
    "Intro: Dragon Road - Night": BASE_ID + 276,
    "Arid Sands - Night": BASE_ID + 277,
    "Intro: Arid Sands - Night": BASE_ID + 278,
    "Skyscraper Scamper - Night": BASE_ID + 279,
    "Intro: Skyscraper Scamper - Night": 1,
    "Intro: Jungle Joyride - Night": 1,
    "Jungle Joyride - Night": 1,
    "Eggmanland - Night": 1,
    "Boss Battle": 1,
    "Boss Battle": 1,
    "vs. Egg Dragoon": 1,
    "vs. Dark Gaia": 1,
    "Super Sonic vs. Dark Gaia": 1,
    "Tornado Defense - 1st Battle": 1,
    "Tornado Defense - 2nd Battle": 1,
    "Apotos - Day": 1,
    "Apotos - Night": 1,
    "Mazuri - Day": 1,
    "Mazuri - Night": 1,
    "Holoska - Day": 1,
    "Holoska - Night": 1,
    "Spagonia - Day": 1,
    "Spagonia - Night": 1,
    "Chun-nan - Day": 1,
    "Chun-nan -Night": 1,
    "Shamar - Day": 1,
    "Shamar - Night": 1,
    "Empire City - Day": 1,
    "Empire City - Night": 1,
    "Adabat - Day": 1,
    "Adabat - Night": 1,
    "Eggmanland Entrance": 1,
    "Result Screen": 1,
    "Result Screen E-Rank": 1,
    "Stage Clear": 1,
    "Boss Stage Clear": 1,
    "Opening Movie - Part 1": 1,
    "Opening Movie - Part 2": 1,

    # Professor's Lab  - Filler
    "TV": 1,
    "Bookshelf": 1,
    "Gramophone": 1,
    "Audio System": 1,

    # Other Fillers
    "Heal Ring": 2,
    "Power Shield": 1,
    "Super Claw": 1,
    "Shield Charge": 1,


}

key_items = {
    "Moon medal": 200,
    "Sun medal": 200
}

filler_items_weight = {
    "CD 1": 1,
    "CD 2": 1,
    "CD 3": 1,
    "ArtWork 1": 1,
    "ArtWork 2": 1,
    "ArtWork 3": 1,
    "Video": 1
}